name: Terraform_Pipeline  # this is the name of the pipeline you can change it as per your requirement

on:       # triggers for the pipeline
  push:
    branches:
      - "feature/new-yml-code-new"  # this is the branch name isi name se feature branch banayenge tabhi pipeline run hogi
  pull_request:
    branches:
      - main

permissions: 
  contents: read
  id-token: write

jobs:
  Terraform-validate:
    name: terraform validate
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./parent

    steps:
      - name: checkout
        uses: actions/checkout@v7

      - name: Gitleaks Secret Scan       #gitleaks secret scan for security purpose
        uses: gitleaks/gitleaks-action@v2

      - name: setup terraform             # terraform setup and installation
        uses: hashicorp/setup-terraform@v2.0.3

      - name: Azure Login              #azure login
        uses: azure/login@v2
        with:                                            #app registration and git secrets me client id, tenant id and subscription id add karna hoga
           client-id: ${{ secrets.AZURE_CLIENT_ID }}
           tenant-id: ${{ secrets.AZURE_TENANT_ID }}
           subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: terraform init

      - name: terraform Formatting
        run: terraform fmt

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan